# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jstaley.github.io
title: Joshua Staley
email: josh@jstaley.com
author: Josh Staley
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/JoshStaley2
  - title: github
    url: https://github.com/jstaley
  - title: linkedin
    url: https://www.linkedin.com/in/joshuastaley
